### ISSUE TITLE
生成后css里引用img路径问题

### ISSUE THREAD

**Issue by xuexb** [laoshu133/grunt-css-sprite#7]
发现通过`sprite`生成的css里的图片路径是, 第个样式都生成一条, 如:

``` css
.icon-7{background-image:url(../images/mod-common.png?20140622130656); background-position:-52px -103px;}
.icon-8{background-image:url(../images/mod-common.png?20140622130656); background-position:-88px -59px;}
.icon-9{background-image:url(../images/mod-common.png?20140622130656); background-position:-18px -103px;}
.icon-10{background-image:url(../images/mod-common.png?20140622130656); background-position:-35px -103px;}
```

如果可以这样感觉会更帅气:

``` css
.icon-21,
.icon-22,
.icon-23,
.icon-24{background-image:url(../images/mod-common.png?20140622130656);}
.icon-21{background-position:-123px -27px;}
.icon-22{background-position:-123px -14px;}
.icon-23{background-position:-123px -53px;}
.icon-24{background-position:-123px -66px;}
```

注: 在这个`sprite for php`看到过 https://github.com/welefen/AutoSprite

最后赞个... 持续关注&使用
